import Head from 'next/head';
// import { Inter } from 'next/font/google';
import matter from 'gray-matter';
import ReactMarkdown from 'react-markdown';
import { Container, Box, Text, Heading, ChakraProvider } from '@chakra-ui/react';
import { Prose } from '@nikolovlazar/chakra-ui-prose';
import { theme } from '@/pages/_app';

export function HomePage({ title, intro }: any) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Container maxW="8xl" w="full" py={20}>
          <Heading as="h1" fontWeight="bold">
            {title}
          </Heading>
          <Prose>
            <Box as={ReactMarkdown}>{intro}</Box>
          </Prose>
        </Container>
      </Box>
    </ChakraProvider>
  );
}

export function HomePagePreview({ entry, widgetFor }: any) {
  const data = {
    title: entry.getIn(['data', 'title']),
    intro: entry.getIn(['data', 'intro']),
  };
  return <HomePage {...data} />;
}
