import Head from 'next/head';
// import { Inter } from 'next/font/google';
import matter from 'gray-matter';
import ReactMarkdown from 'react-markdown';
import { Container, Box, Text, Heading } from '@chakra-ui/react';
import { Prose } from '@nikolovlazar/chakra-ui-prose';

export default function Home({ data }: any) {
  // console.log({ data });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Container maxW="8xl" w="full" py={20}>
          <Heading as="h1" fontWeight="bold">
            {data.title}
          </Heading>
          <Prose>
            <Box as={ReactMarkdown}>{data.intro}</Box>
          </Prose>
        </Container>
      </Box>
    </>
  );
}

export async function getStaticProps() {
  const m = matter.read('./content/pages/home.md');
  return {
    props: { data: m.data },
  };
}
